Syncing master branch with upstream master (#53)
* [external contributor] Support config providers in validation by @swehner (#753)

Co-authored-by: Stefan Wehner <stefan@revenuecat.com>

* v2.1.2 release change in master (#757)

git cherry-pick d4d0e87

* NO-SNOW: Expose the Ingest SDK MAX_CLIENT_LAG configuration in KC  (#758)

* Add authentication for max lag parameter and fix IT (#763)

* SNOW-989387: Fix for java.lang.NoClassDefFoundError (#774)

java.lang.NoClassDefFoundError: Could not initialize class net.snowflake.client.jdbc.internal.apache.arrow.memory.RootAllocator occurs when the JDBC driver tries to process the result of the offset migration query. This is a known long-standing issue in the JDBC driver so a workaround is introduced with this fix.

* [SNOW-1015644] Update ingest sdk to 2.0.5 (#778)

* SNOW-943288, SNOW-938379: Fix two schema evolution cases that could cause non-exactly once delivery (#775)

Fix two exactly once delivery behavior issues with Snowpipe Streaming:

- When there're gaps between offsets due to records being put into the DLQ or NULL records being skipped, the current logic doesn't work after a channel reopening event (e.g. schema evolution) since it expects continuous offsets in order to guarantee exactly once delivery, causing ingestion to stop.
- When a flush is triggered by size or rowcount threshold, it's possible that only partial rows in the buffer are flushed and with a channel reopening event (e.g. schema evolution), currently the leftover rows in the buffer are still being considered which is causing the offset to be advanced and skip some offsets.

The fix in this PR makes sure we won't flush any leftover rows in the buffer, they will all be skipped and discarded. The next batch should start from the expected offset after the offset reset as part of the channel reopening event.

* resolves issue with generating and building java libary (#780)

* [SNOW-88848] Update readme with Snowflake documentation (#781)

* Update version to 2.2.0 for release (#779)

* Downgrade JDBC to 3.13.30 (#783)

* SNOW-922795 Added third-party-licenses to .zip distribution (#784)

* PROD-39429 Add PR template (#786)

---------

Co-authored-by: revi cheng <revi.cheng@snowflake.com>
Co-authored-by: Stefan Wehner <stefan@revenuecat.com>
Co-authored-by: Toby Zhang <toby.zhang@snowflake.com>
Co-authored-by: Waleed Fateem <72769898+sfc-gh-wfateem@users.noreply.github.com>
Co-authored-by: Greg Jachimko <greg.jachimko@snowflake.com>
Co-authored-by: Michał Bobowski <145468486+sfc-gh-mbobowski@users.noreply.github.com>
Co-authored-by: Jay Patel <jay.patel@snowflake.com>